### ISSUE TITLE
Any documentation on methods and use beyond the Test app?

### ISSUE THREAD

**Issue by lonnietc** [jchristn/Gatekeeper#2]
Hello,

I am looking to add RBAC into a type of graph database application that I am developing and am interested in your Gatekeeper library.

I would like to ask if there is any more documentation beyond the Test application since I am trying to get a good feel for how to use the methods and call correctly?

Thanks

**Comment by jchristn** [comment]
Hello and thanks for your note. I do not have additional documentation but I am happy to answer any specific questions that you have here! I've really only been maintaining the library over the past couple of years it was originally released a few years ago and I haven't spent much time on enhancing it. Looking at the code I feel is probably overdue for a re-factor for simplicity.

At any rate please feel free to ask questions here and I'll be happy to answer them. Cheers

**Comment by jchristn** [comment]
Hi, just wanted to let you know I started a major refactor and will include as part of that an overhaul of the documentation. Cheers

**Comment by jchristn** [comment]
Hi @lonnietc I refactored the package end to end and cleaned up a lot of packaging issues (for instance, now the XML documentation is packed and included).  Several new APIs introduced, and the test application (GateKeeperConsole) is now a lot more useful.  Updated the README as well.  Would love to have you take a look and provide feedback!  Please re-open if any comments/concerns/feedback!  Cheers, Joel

NuGet: https://www.nuget.org/packages/GateKeeper/2.0.1
Commit: https://github.com/jchristn/Gatekeeper/commit/34ac4eaa6c3297cd6284a47e065831acd5719782

**Comment by lonnietc** [comment]
Thanks for refactoring and I will be able to try it soon as I am working on the core code now and in just a couple of weeks should be able to incorporate it.

My project is a type of Graph database in which I want to have fine granular RBAC and ACL in place for user to access graphs, as well as fine grained enough to control access to various graph Nodes & Relations and their properties.  This graph database will also have a significant built-in ability for Event_triggers (traversals, timers, dates, actions, etc.) into the Nodes & Relations and their properties as well.

Will let you know more when I get to that point, ok.

**Comment by jchristn** [comment]
Awesome, I built a small graph engine called [LiteGraph](https://github.com/jchristn/LiteGraph) which uses sqlite behind the scenes.  If it's of any value to you, feel free to leverage any of the code (it's MIT licensed)
